@SharesApp.Server_HostAddress = http://localhost:5239

GET {{SharesApp.Server_HostAddress}}/security/
Accept: application/json
###

GET {{SharesApp.Server_HostAddress}}/moex/
Accept: application/json
###
