name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - # Checkout to the repository on the build machine
      name: Checkout 
      uses: actions/checkout@v4
      
    - # Login to Docker Hub using the secrets provided
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_TOKEN}}
        
    - # Create a build kit builder instance
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - # Build the container image and push it to Docker \
      # Hub with the name sharesapptoken
      name: Build and push
      uses: docker/build-push-action@v4
      with:
          context: .
          file: ./SharesApp.Server/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/sharesappimage:latest
          build-args: |
            DATABASE_USER=${{ DATABASE_USER }}
            DATABASE_PASSWORD=${{ DATABASE_PASSWORD }}
